### ISSUE TITLE
Code Example in README Not Working due to case sensitivity

### ISSUE THREAD

**Issue by philipemosv** [GabrielCSTR/d2pt.js#1]
The code example provided in the README is not functioning as expected due to case sensitivity. The parameter "MID" is in all caps, which prevents it from returning any data. Should be either mid or Mid.

Thank you!

**Comment by gbrlstr** [comment]
Thanks for the report. I will be adjusting and uploading new settings and test files.

If you have any improvements or ideas, you can open a pull request and I will analyze it.

Thank you!
